kind: pipeline
name: drone_kube_build

trigger:
  ref:
    - refs/heads/master
    - refs/tags/v*

clone:
  depth: 1

steps:
  - name: build_source_code
    image: golang:1.6
    volumes:
      - name: deps
        path: /go
    environment:
      CGO_ENABLED: 0
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo

  - name: build_docker_image
    image: plugins/docker
    repo: zfeng/drone-kube
    settings:
      auto_tag: true
      username:
        from_secret: docker_repository_username
      password:
        from_secret: docker_repository_password

volumes:
  - name: deps
    temp: {}
